"""Per-feature normalization statistics (GENERATED -- do not edit by hand).

Generated by compute_norm_stats.py from dataset: circuit-noise-600.h5
Shots used: 600

Regenerate with::

    pixi run python -m self_interferometry.analysis.features.compute_norm_stats <dataset.h5>
"""

NORMALIZATION_STATS: dict[str, dict[str, float]] = {
    'pd_RP1_CH2': {'mean': 0.0008673048737906442, 'std': 0.0013602655274585138},
    'pd_RP2_CH1': {'mean': 0.00015775388030256465, 'std': 0.016663807256303485},
    'pd_RP2_CH2': {'mean': 0.0003480221760462854, 'std': 0.0011829063723140674},
    'velocity': {'mean': -3.772807157057893e-09, 'std': 769.7645869367719},
    'displacement': {'mean': 0.06497811690687316, 'std': 0.9112738354694614},
}
