model:
  # Common parameters for all model types
  role: "standard" # "standard" or "ensemble"
  type: "FNO"
  input_size: 16384  # Used for validation, FNO processes full sequence
  output_size: 16384  # Used for validation, FNO processes full sequence
  in_channels: 3
  # FNO specific parameters
  n_modes: [32, 64]  # Number of modes for 1D FNO (list gets converted to tuple)
  hidden_channels: [8,16]
  n_layers: 4
  max_n_modes: null
  fno_block_precision: "full"
  use_channel_mlp: false # using a channel mlp seems to always lead to overtraining
  channel_mlp_dropout: 0.2
  channel_mlp_expansion: 0.5
  non_linearity: "gelu"  # FNO internal activation function
  stabilizer: null
  norm: null
  preactivation: false
  fno_skip: "linear"
  channel_mlp_skip: "soft-gating"
  separable: false
  factorization: null
  rank: 1.0
  joint_factorization: false
  fixed_rank_modes: false
  implementation: "factorized"
  decomposition_kwargs: null

training:
  max_epochs: 500
  warmup_epochs: 0
  T_0: 50  # Initial restart period (epochs for first cosine cycle)
  T_mult: 1  # Factor to increase T_i after each restart (1 = constant period, 2 = doubling)
  batch_size: 128
  optimizer: "Adam"  # Options: "Adam", "SGD", "Muon"
  momentum: 0.9 # Unused if optimizer is not SGD
  weight_decay: 1e-4 # Unused if optimizer is not Adam
  learning_rate: 1e-2
  eta_min: 1e-4
  accelerator: "gpu"
  devices: 1
  use_logging: true
  wandb_project: "self-interferometry"
  experiment_name: "fno_vel_target_disp_shift"
  checkpoint_dir: "./analysis/checkpoints"
  target: "velocity"  # "velocity" or "displacement" - what the model predicts

loss:
  dynamic: false # enable dynamic loss weighting, overrides weights below
  velocity_loss_weight: 1.0
  displacement_loss_weight: 0.0

data:
  data_dir: "./analysis/data"
  dataset_file: "train5000.h5"
  split_ratios: [80, 10, 10]  # train, val, test percentages
  split_seed: 42
  num_workers: 7
  channel_dropout: 0.0  # chance of dropping a channel during training