model:
  type: "SCNN"
  sequence_length: 16384
  activation: "GELU"
  use_layer_norm: true
  use_weight_norm: true
  dropout: 0.0
  in_channels: 3
  # SCNN specific parameters
  kernel_size: [3, 5, 7]
  temporal_channels: [[16, 16, 32, 32, 64, 64]]
  dilation_base: [2, 3, 4] 

training:
  max_epochs: 200
  warmup_epochs: 0
  T_0: 200
  T_mult: 1
  batch_size: 128
  optimizer: "Muon"
  weight_decay: 1e-6
  momentum: 0.9
  learning_rate: 1e-3
  eta_min: 1e-6
  accelerator: "gpu"
  devices: 1
  use_logging: true
  wandb_project: "self-interferometry"
  experiment_name: "scnn_pareto_recep_scan"
  checkpoint_dir: "./analysis/checkpoints"
  target: "velocity"

loss:
  dynamic: false
  velocity_loss_weight: 1.0
  displacement_loss_weight: 0.0

data:
  data_dir: "./analysis/data"
  dataset_file: ["free-space-synchro_10k.h5", "mmfiber-synchro_10k.h5"]
  split_ratios: [[80, 10, 10]]
  split_seed: 42
  num_workers: 7

