model:
  type: "UTCN"
  sequence_length: 16384
  activation: "GELU" # GELU better than LeakyReLU
  use_layer_norm: true 
  use_weight_norm: true
  in_channels: 3

  # UTCN specific parameters
  kernel_size: 7  # Kernel size for all temporal blocks

  # UTCN layer-wise configuration (must all be same length as n_layers)
  # For a 5-layer UTCN: layers 0-1 are encoder, layer 2 is bottleneck, layers 3-4 are decoder
  # Fewer channels in middle layers with larger dilations
  temporal_channels: [[64, 32, 16, 8, 16, 32, 64], [16,16,16,16,16,16,16], [8,16,32,64,32,16,8], [32, 32, 32, 32, 32, 32, 32]] # [[64, 32, 16, 32, 64]]  # Output channels for each layer
  temporal_dilations: [[1,4,11,31,11,4,1]] # [4,16,64,128,64,16,4] best so far, 256 dilation in middle is too much  # Dilation factors per layer (increase then decrease)
# So far, best results from largest dilation in middle layer

  # Skip connections (default: symmetric U-Net skips)
  horizontal_skips_map: null  # null uses default: {4: 0, 3: 1} for 5 layers
  horizontal_skip: "linear"  # Type of horizontal skip connections ('linear' or 'identity')

training:
  max_epochs: 500
  warmup_epochs: 0
  T_0: 500  # Initial restart period (epochs for first cosine cycle)
  T_mult: 1  # Factor to increase T_i after each restart (1 = constant period, 2 = doubling)
  batch_size: 128
  optimizer: "Muon"  # Options: "Adam", "SGD", "Muon"; Muon performs best so far
  momentum: 0.9 # Unused if optimizer is not SGD
  weight_decay: 1e-6 # free-space: 1e-6, fiber: ?
  learning_rate: 1e-3 # 1e-2 too large, 1e-3 is good
  eta_min: 0e-6
  accelerator: "gpu"
  devices: 1
  use_logging: true
  wandb_project: "self-interferometry"
  experiment_name: "utcn_pareto_search"
  checkpoint_dir: "./analysis/checkpoints"
  target: "velocity"  # "velocity" or "displacement" - what the model predicts

loss:
  dynamic: false # enable dynamic loss weighting, overrides weights below
  velocity_loss_weight: 1.0
  displacement_loss_weight: 0.0

data:
  data_dir: "./analysis/data"
  dataset_file: ["free-space-synchro_10k.h5", "mmfiber-synchro_10k.h5"]
  split_ratios: [[80, 10, 10]]  # train, val, test percentages
  split_seed: 42
  num_workers: 7
