"""Compute per-feature normalization statistics from a dataset.

Points at an HDF5 dataset, evaluates every registered feature
(:data:`~smi.analysis.features.registry.default_registry`) for
each shot, and writes per-feature mean/std to ``normalization.py`` for version
control. Models bake these stats into ``register_buffer`` s (see
``analysis/models/base.py``) so internal layers see zero-mean/unit-variance
features while the rest of the codebase works in raw physical units.

Usage::

    pixi run python -m smi.analysis.features.compute_norm_stats \
        smi/analysis/data/circuit-noise-600.h5
"""

import argparse
import logging
from pathlib import Path

import h5py
import numpy as np

from smi.redpitaya.redpitaya_config import RedPitayaConfig

from .registry import default_registry

logger = logging.getLogger(__name__)

EPSILON = 1e-8
VOLTAGE_KEY = 'RP1_CH1'
PD_CHANNEL_KEYS = ('RP1_CH2', 'RP2_CH1', 'RP2_CH2')
ALL_CHANNELS = (VOLTAGE_KEY, *PD_CHANNEL_KEYS)


def _resolve_sample_rate(f: h5py.File) -> float:
    """Read the sample rate from file attrs, falling back to the dec-256 rate."""
    if 'sample_rate' in f.attrs:
        return float(f.attrs['sample_rate'])
    default = RedPitayaConfig.SAMPLE_RATE_DEC1 / 256
    logger.warning('No sample_rate attr; using default %.2f Hz', default)
    return default


def compute_stats(dataset_path: str | Path, chunk_size: int = 500) -> dict[str, dict]:
    """Compute mean/std for every registered feature across all shots.

    Statistics are pooled over both the shot and time axes (matching the
    historical per-channel z-score), using a single streaming pass.

    Args:
        dataset_path: Path to the HDF5 dataset.
        chunk_size: Number of shots to load per chunk.

    Returns:
        Mapping feature name -> {'mean': float, 'std': float}, plus a
        ``'_meta'`` entry recording the source and shot count.
    """
    dataset_path = Path(dataset_path)
    feature_names = (
        default_registry.input_features() + default_registry.target_features()
    )
    sums = dict.fromkeys(feature_names, 0.0)
    sq_sums = dict.fromkeys(feature_names, 0.0)
    counts = dict.fromkeys(feature_names, 0)

    with h5py.File(dataset_path, 'r') as f:
        for ch in ALL_CHANNELS:
            if ch not in f:
                raise ValueError(f"Channel '{ch}' not found in {dataset_path}")
        sample_rate = _resolve_sample_rate(f)
        n_shots = len(f[VOLTAGE_KEY])

        for start in range(0, n_shots, chunk_size):
            end = min(start + chunk_size, n_shots)
            chunk = {ch: np.asarray(f[ch][start:end]) for ch in ALL_CHANNELS}
            for i in range(end - start):
                raw = {ch: chunk[ch][i] for ch in ALL_CHANNELS}
                raw['sample_rate'] = sample_rate
                computed = default_registry.compute(raw, feature_names)
                for name, arr in computed.items():
                    flat = np.asarray(arr, dtype=np.float64).ravel()
                    sums[name] += float(flat.sum())
                    sq_sums[name] += float((flat**2).sum())
                    counts[name] += flat.size

    stats: dict[str, dict] = {}
    for name in feature_names:
        n = counts[name]
        mean = sums[name] / n
        var = sq_sums[name] / n - mean**2
        std = max(float(np.sqrt(max(var, 0.0))), EPSILON)
        stats[name] = {'mean': float(mean), 'std': std}

    stats['_meta'] = {'source': dataset_path.name, 'n_shots': int(n_shots)}
    return stats


def write_normalization_module(stats: dict[str, dict], out_path: Path) -> None:
    """Render ``stats`` to a version-controllable Python module."""
    meta = stats.get('_meta', {})
    lines = [
        '"""Per-feature normalization statistics (GENERATED -- do not edit by hand).',
        '',
        f'Generated by compute_norm_stats.py from dataset: {meta.get("source", "?")}',
        f'Shots used: {meta.get("n_shots", "?")}',
        '',
        'Regenerate with::',
        '',
        '    pixi run python -m smi.analysis.features.compute_norm_stats <dataset.h5>',
        '"""',
        '',
        'NORMALIZATION_STATS: dict[str, dict[str, float]] = {',
    ]
    for name, vals in stats.items():
        if name == '_meta':
            continue
        lines.append(
            f"    {name!r}: {{'mean': {vals['mean']!r}, 'std': {vals['std']!r}}},"
        )
    lines.append('}')
    lines.append('')
    out_path.write_text('\n'.join(lines))


def main() -> None:
    """CLI entry point."""
    logging.basicConfig(level=logging.INFO)
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('dataset', help='Path to the HDF5 dataset')
    parser.add_argument(
        '--out',
        default=str(Path(__file__).parent / 'normalization.py'),
        help='Output path for the generated normalization module',
    )
    args = parser.parse_args()

    stats = compute_stats(args.dataset)
    write_normalization_module(stats, Path(args.out))
    logger.info('Wrote normalization stats to %s', args.out)
    for name, vals in stats.items():
        if name != '_meta':
            logger.info('  %s: mean=%.6g std=%.6g', name, vals['mean'], vals['std'])


if __name__ == '__main__':
    main()
