"""Model normalization wrapper and feature-map layer.

``Model`` wraps an inner network (one of the architectures in this package) and
bakes input/output normalization into ``register_buffer`` s. Internally the
network sees zero-mean / unit-variance inputs and is trained against scaled
outputs, but ``Model`` exposes a raw-units interface: raw photodiode signals in,
raw velocity/displacement out. The rest of the codebase (loss, plotting,
metrics) therefore keeps working in raw physical units, and the trained model is
self-contained for packaging (the normalization travels with the weights, e.g.
through TorchScript export).

Forward data flow (all shapes ``[batch, channels, length]``)::

    raw_x -> FeatureMap -> (x - input_mean)/input_std -> inner -> out*std+mean -> raw

The statistics come from the version-controlled
``analysis/features/normalization.py`` (generated by ``compute_norm_stats.py``).
"""

import numpy as np
import torch
from torch import Tensor, nn


class FeatureMap(nn.Module):
    """Input feature transform baked into the model (currently identity).

    This is the TorchScript-compatible counterpart to the Polars
    ``FeatureRegistry``: when hand-crafted input features are introduced, their
    differentiable/array form lives here so that a packaged (scripted) model can
    perform the same feature engineering on raw device outputs. There is no
    feature engineering yet, so it is an identity passthrough.
    """

    def forward(self, x: Tensor) -> Tensor:
        """Return the input unchanged (identity feature map)."""
        return x


class Model(nn.Module):
    """Normalization wrapper around an inner sequence model.

    Args:
        inner: The wrapped network. Maps ``[B, C, L]`` (normalized) to
            ``[B, 1, L]`` (scaled-output space).
        input_mean: Per-input-channel means, shape ``[C]``.
        input_std: Per-input-channel std deviations, shape ``[C]``.
        output_mean: Scalar mean of the target feature.
        output_std: Scalar std of the target feature.
    """

    def __init__(
        self,
        inner: nn.Module,
        input_mean: np.ndarray | Tensor,
        input_std: np.ndarray | Tensor,
        output_mean: float,
        output_std: float,
    ) -> None:
        super().__init__()
        self.feature_map = FeatureMap()
        self.inner = inner

        in_mean = torch.as_tensor(input_mean, dtype=torch.float32).reshape(1, -1, 1)
        in_std = torch.as_tensor(input_std, dtype=torch.float32).reshape(1, -1, 1)
        self.register_buffer('input_mean', in_mean)
        self.register_buffer('input_std', in_std)
        self.register_buffer(
            'output_mean', torch.tensor(float(output_mean)).reshape(1, 1, 1)
        )
        self.register_buffer(
            'output_std', torch.tensor(float(output_std)).reshape(1, 1, 1)
        )

    @classmethod
    def from_registry_stats(
        cls,
        inner: nn.Module,
        input_feature_names: list[str],
        target_name: str,
        stats: dict[str, dict[str, float]],
    ) -> 'Model':
        """Build a ``Model`` from a normalization-stats mapping.

        Args:
            inner: The wrapped network.
            input_feature_names: Feature names whose stats scale the inputs, in
                channel order.
            target_name: Feature name whose stats scale the output.
            stats: Mapping ``feature -> {'mean', 'std'}`` (e.g.
                ``NORMALIZATION_STATS``).
        """
        input_mean = np.array([stats[n]['mean'] for n in input_feature_names])
        input_std = np.array([stats[n]['std'] for n in input_feature_names])
        return cls(
            inner,
            input_mean=input_mean,
            input_std=input_std,
            output_mean=stats[target_name]['mean'],
            output_std=stats[target_name]['std'],
        )

    @classmethod
    def identity(cls, inner: nn.Module, in_channels: int) -> 'Model':
        """Build a ``Model`` whose normalization is a no-op (mean 0, std 1).

        Used when input/output statistics do not apply (e.g. on-device synthetic
        data with a different scale), keeping the wrapper interface uniform while
        leaving the signal untouched.
        """
        return cls(
            inner,
            input_mean=np.zeros(in_channels),
            input_std=np.ones(in_channels),
            output_mean=0.0,
            output_std=1.0,
        )

    def forward(self, x: Tensor) -> Tensor:
        """Raw inputs ``[B, C, L]`` -> raw outputs ``[B, 1, L]``."""
        x = self.feature_map(x)
        x = (x - self.input_mean) / self.input_std
        out = self.inner(x)
        return out * self.output_std + self.output_mean

    @torch.jit.unused
    def encode(self, x: Tensor) -> object:
        """Delegate to ``inner.encode`` on normalized inputs (for VICReg).

        Excluded from TorchScript: only ``forward`` is part of the packaged
        interface, and not every inner model defines ``encode``.
        """
        x = self.feature_map(x)
        x = (x - self.input_mean) / self.input_std
        return self.inner.encode(x)

    @property
    def total_params(self) -> int:
        """Trainable parameter count of the inner model."""
        return sum(p.numel() for p in self.inner.parameters() if p.requires_grad)

    @property
    def receptive_field(self) -> int | None:
        """Receptive field of the inner model if it exposes one."""
        return getattr(self.inner, 'receptive_field', None)

    def to_torchscript(self) -> torch.jit.ScriptModule:
        """Compile this wrapped model to TorchScript for packaging/export.

        TorchScript is the packaging path (a self-contained artifact that takes
        raw device outputs); ``torch.compile`` remains the training-speed path.
        """
        return torch.jit.script(self)
