model:
  type: "CNN"
  dropout: 0.1

training:
  max_epochs: 500
  batch_size: 8
  optimizer: "Adam"
  learning_rate: 5e-4
  T_max: 500
  eta_min: 0
  accelerator: "cpu"
  devices: '1'
  use_logging: false
  wandb_project: "self-interferometry"
  experiment_name: "teacher_pipeline"
  checkpoint_dir: "./signal_analysis/checkpoints"

loss:
  use_encoding_loss: true
  encoding_weight: 1.0

data:
  data_dir: "./signal_analysis/data"
  train_file: "train.h5"
  val_file: "val.h5"
  test_file: "test.h5"
  num_workers: 7
  dataset_params:
    train_samples: 10
    val_samples: 1
    test_samples: 1
