model:
  # Common parameters for all model types
  role: "standard" # "standard" or "ensemble" or "teacher" or "student"
  type: "TCN"  # "CNN" or "TCN" or "FCN"
  activation: "LeakyReLU"
  in_channels: 3
  dropout: 0.1
  kernel_size: 7

training:
  max_epochs: [200, 200]
  batch_size: 64
  optimizer: "Adam"
  learning_rate: 1e-2
  T_max: 200
  eta_min: 0
  accelerator: "gpu"
  devices: 1
  use_logging: true
  wandb_project: "self-interferometry"
  experiment_name: "shot_delay_1pt0"
  checkpoint_dir: "./signal_analysis/checkpoints"

loss:
  physics_weight: 1.0

data:
  data_dir: "./signal_analysis/data"
  train_file: "train1pt0.h5"
  val_file: "val1pt0.h5"
  test_file: "test1pt0.h5"
  # pretraining data is simulated, mainly used for training teacher model
  pretrain_file: "pretrain.h5"
  preval_file: "preval.h5"
  pretest_file: "pretest.h5"
  num_workers: 7
  dataset_params:
    train_samples: 200
    val_samples: 50
    test_samples: 50
