model:
  # Common parameters for all model types
  role: ["standard", "ensemble"] # "standard" or "ensemble" or "teacher" or "student"
  type: "TCN"  # "CNN" or "TCN" or "FCN"
  activation: ["LeakyReLU", "Tanh"]
  in_channels: [3, 3, 3]
  dropout: 0.1
  kernel_size: 7
  num_channels: [[32, 32, 64, 64]]
  dilation_base: 7
  stride: 1

training:
  max_epochs: 500
  batch_size: 64
  optimizer: ["SGD", "Adam"]
  learning_rate: 7e-2
  eta_min: 0
  accelerator: "cpu"
  devices: 1
  use_logging: false
  wandb_project: "self-interferometry"
  experiment_name: "tcn_100kHz_test"
  checkpoint_dir: "./signal_analysis/checkpoints"

loss:
  velocity_loss_weight: 1.0
  displacement_loss_weight: 1.0

data:
  data_dir: "./signal_analysis/data"
  train_file: "test-100kHz-500.h5"
  val_file: "val-100kHz-500.h5"
  test_file: "test-100kHz-500.h5"
  # pretraining data is simulated, mainly used for training teacher model
  pretrain_file: "pretrain.h5"
  preval_file: "preval.h5"
  pretest_file: "pretest.h5"
  num_workers: 7
  channel_dropout: 0.5  # chance of dropping a channel during training
  dataset_params:
    train_samples: 5000
    val_samples: 500
    test_samples: 500
