model:
  # Common parameters for all model types
  role: "standard" # "standard" or "ensemble"
  type: "CNN"  # "CNN" or "TCN"
  input_size: 256
  output_size: 1
  activation: "LeakyReLU"
  in_channels: 3
  dropout: 0.1
  # BarlandCNN specific parameters
  window_stride: 128

training:
  max_epochs: 500
  batch_size: 256
  optimizer: "Adam"
  learning_rate: 7e-2
  eta_min: 0
  accelerator: "gpu"
  devices: 1
  use_logging: true
  wandb_project: "self-interferometry"
  experiment_name: "barland_cnn_training"
  checkpoint_dir: "./analysis/checkpoints"

loss:
  velocity_loss_weight: 1.0
  displacement_loss_weight: 0.1

data:
  data_dir: "./analysis/data"
  train_file: "train-mmfiber-5000.h5"
  val_file: "val-mmfiber-500.h5"
  test_file: "test-mmfiber-500.h5"
  num_workers: 7
  channel_dropout: 0.5  # chance of dropping a channel during training
  dataset_params:
    train_samples: 5000
    val_samples: 500
    test_samples: 500